### Parent-Student Relationship API Tests

@baseUrl = http://localhost:8080
@parentUserId = 5
@studentUserId = 4

### Link parent to student
POST {{baseUrl}}/parents/{{parentUserId}}/students
Content-Type: application/json

{
  "studentUserId": {{studentUserId}}
}

### Get all students for a parent
GET {{baseUrl}}/parents/{{parentUserId}}/students

### Get all parents for a student
GET {{baseUrl}}/parents/students/{{studentUserId}}/parents

### Check if parent is linked to student
GET {{baseUrl}}/parents/{{parentUserId}}/students/{{studentUserId}}/linked

### Unlink parent from student
DELETE {{baseUrl}}/parents/{{parentUserId}}/students/{{studentUserId}}

# Made with Bob